println 24
println 'v    >"EMIRP TON"CCCCCCCCCE '
println '>DD2-:"EMIRP"CCCCCE'
println '     D'
println '     D'
println '     2'
println '     /'
println '     2'
println '     *'
println '     -'
println ' >v3D:'
println ' XD  >"EMIRP TON"CCCCCCCCCE '
println ' 3D'
println ' DD'
println ' D4'
println ' XX'
println ' 11'
println ' +X'
println ' 2/'
println '>:D"EMIRP TON"CCCCCCCCCE '
println '- 2'
println 'X X'
println '2 -'
println '^*:"EMIRP"CCCCCE'
println '^*<'
