println 20
println 'v   >"EMIRP TON"CCCCCCCCCE '
println '>D2-:"EMIRP"CCCCCE'
println '    D'
println '    D'
println '    2'
println '   >v'
println '   XD'
println '   3D'
println '   DD'
println '   D4'
println '   XX'
println '   11'
println '   +X'
println '   1/'
println ' >-:D"EMIRP TON"CCCCCCCCCE '
println ' X  2'
println ' 2  X'
println ' *  -'
println ' ^  :"EMIRP"CCCCCE'
println ' ^  <'
