[package]
name = "solution"
version.workspace = true
edition.workspace = true
authors.workspace = true
autobins = false

[[bin]]
name = "example"
path = "example.rs"

[[bin]]
name = "bronze"
path = "bronze.rs"

[[bin]]
name = "wait"
path = "wait.rs"

[[bin]]
name = "greedy"
path = "greedy.rs"

[[bin]]
name = "fuzz"
path = "fuzz.rs"

[[bin]]
name = "trunk"
path = "trunk.rs"

[[bin]]
name = "bulwark"
path = "bulwark.rs"

[[bin]]
name = "champ"
path = "champ.rs"

[[bin]]
name = "corridor"
path = "corridor.rs"

[[bin]]
name = "rampart"
path = "rampart.rs"

[[bin]]
name = "warden"
path = "warden.rs"

[[bin]]
name = "vanguard"
path = "vanguard.rs"

[[bin]]
name = "probe"
path = "probe.rs"

[[bin]]
name = "augur"
path = "augur.rs"

[[bin]]
name = "sentinel"
path = "sentinel.rs"

[[bin]]
name = "echo"
path = "echo.rs"

[dependencies]
