[package]
name = "solution"
version.workspace = true
edition.workspace = true
authors.workspace = true
autobins = false

[[bin]]
name = "bronze"
path = "bronze.rs"

[[bin]]
name = "wait"
path = "wait.rs"

[[bin]]
name = "greedy"
path = "greedy.rs"

[[bin]]
name = "fuzz"
path = "fuzz.rs"

[dependencies]
